<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSvXF60h\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSvXF60h/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSvXF60h.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSvXF60h\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSvXF60h\App_KernelDevDebugContainer([
    'container.build_hash' => 'SvXF60h',
    'container.build_id' => '635ad8d8',
    'container.build_time' => 1780297811,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSvXF60h');
