<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHgPLNUa\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHgPLNUa/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHgPLNUa.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHgPLNUa\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHgPLNUa\App_KernelDevDebugContainer([
    'container.build_hash' => 'HgPLNUa',
    'container.build_id' => '4f7ecf8e',
    'container.build_time' => 1774809371,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHgPLNUa');
