<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTYoVI0R\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTYoVI0R/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTYoVI0R.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTYoVI0R\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTYoVI0R\App_KernelDevDebugContainer([
    'container.build_hash' => 'TYoVI0R',
    'container.build_id' => 'a02c7122',
    'container.build_time' => 1776062552,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTYoVI0R');
