<?php

namespace ContainerTYoVI0R;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFontsPruneCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'NeuralGlitch\GoogleFonts\Command\FontsPruneCommand' shared autowired service.
     *
     * @return \NeuralGlitch\GoogleFonts\Command\FontsPruneCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/neuralglitch/google-fonts/src/Command/FontsPruneCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/filesystem/Filesystem.php';

        $container->privates['NeuralGlitch\\GoogleFonts\\Command\\FontsPruneCommand'] = $instance = new \NeuralGlitch\GoogleFonts\Command\FontsPruneCommand(\dirname(__DIR__, 4), (\dirname(__DIR__, 4).'/assets/fonts'), (\dirname(__DIR__, 4).'/assets/fonts.json'), ($container->privates['NeuralGlitch\\GoogleFonts\\Service\\FontLockManager'] ?? $container->load('getFontLockManagerService')), ($container->privates['filesystem'] ??= new \Symfony\Component\Filesystem\Filesystem()));

        $instance->setName('gfonts:prune');
        $instance->setDescription('Remove unused fonts from locked fonts');

        return $instance;
    }
}
