<?php

namespace ContainerTYoVI0R;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFontsLockCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.NeuralGlitch\GoogleFonts\Command\FontsLockCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.NeuralGlitch\\GoogleFonts\\Command\\FontsLockCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('gfonts:lock', [], 'Scan templates and lock all used fonts for production', false, #[\Closure(name: 'NeuralGlitch\\GoogleFonts\\Command\\FontsLockCommand')] fn (): \NeuralGlitch\GoogleFonts\Command\FontsLockCommand => ($container->privates['NeuralGlitch\\GoogleFonts\\Command\\FontsLockCommand'] ?? $container->load('getFontsLockCommandService')));
    }
}
