<?php

namespace ContainerW0Rb4xE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActionsFranceControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YwLLdgS.App\Controller\Front\ActionsFranceController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YwLLdgS.App\\Controller\\Front\\ActionsFranceController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'franceSectionRepository' => ['privates', 'App\\Repository\\FranceSectionRepository', 'getFranceSectionRepositoryService', true],
            'rubricInfoRepository' => ['privates', 'App\\Repository\\RubricInfoRepository', 'getRubricInfoRepositoryService', true],
            'actionRepository' => ['privates', 'App\\Repository\\ActionRepository', 'getActionRepositoryService', true],
        ], [
            'franceSectionRepository' => 'App\\Repository\\FranceSectionRepository',
            'rubricInfoRepository' => 'App\\Repository\\RubricInfoRepository',
            'actionRepository' => 'App\\Repository\\ActionRepository',
        ]))->withContext('App\\Controller\\Front\\ActionsFranceController::index()', $container);
    }
}
