<?php

namespace ContainerW0Rb4xE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActionsBeninControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YKtU2F0.App\Controller\Front\ActionsBeninController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YKtU2F0.App\\Controller\\Front\\ActionsBeninController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'beninSectionRepository' => ['privates', 'App\\Repository\\BeninSectionRepository', 'getBeninSectionRepositoryService', true],
            'rubricInfoRepository' => ['privates', 'App\\Repository\\RubricInfoRepository', 'getRubricInfoRepositoryService', true],
        ], [
            'beninSectionRepository' => 'App\\Repository\\BeninSectionRepository',
            'rubricInfoRepository' => 'App\\Repository\\RubricInfoRepository',
        ]))->withContext('App\\Controller\\Front\\ActionsBeninController::index()', $container);
    }
}
