<?php

namespace ContainerW0Rb4xE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContactControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8vsY0c0.App\Controller\Front\ContactController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8vsY0c0.App\\Controller\\Front\\ContactController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'contactSectionRepository' => ['privates', 'App\\Repository\\ContactSectionRepository', 'getContactSectionRepositoryService', true],
            'rubricInfoRepository' => ['privates', 'App\\Repository\\RubricInfoRepository', 'getRubricInfoRepositoryService', true],
        ], [
            'contactSectionRepository' => 'App\\Repository\\ContactSectionRepository',
            'rubricInfoRepository' => 'App\\Repository\\RubricInfoRepository',
        ]))->withContext('App\\Controller\\Front\\ContactController::index()', $container);
    }
}
