<?php

namespace ContainerW0Rb4xE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFontsImportCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.NeuralGlitch\GoogleFonts\Command\FontsImportCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.NeuralGlitch\\GoogleFonts\\Command\\FontsImportCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('gfonts:import', [], 'Import and download a Google Font for local use', false, #[\Closure(name: 'NeuralGlitch\\GoogleFonts\\Command\\FontsImportCommand')] fn (): \NeuralGlitch\GoogleFonts\Command\FontsImportCommand => ($container->privates['NeuralGlitch\\GoogleFonts\\Command\\FontsImportCommand'] ?? $container->load('getFontsImportCommandService')));
    }
}
