<?php

namespace ContainerW0Rb4xE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFontsSearchCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'NeuralGlitch\GoogleFonts\Command\FontsSearchCommand' shared autowired service.
     *
     * @return \NeuralGlitch\GoogleFonts\Command\FontsSearchCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/neuralglitch/google-fonts/src/Command/FontsSearchCommand.php';

        $container->privates['NeuralGlitch\\GoogleFonts\\Command\\FontsSearchCommand'] = $instance = new \NeuralGlitch\GoogleFonts\Command\FontsSearchCommand(($container->privates['NeuralGlitch\\GoogleFonts\\Service\\GoogleFontsApi'] ?? $container->load('getGoogleFontsApiService')));

        $instance->setName('gfonts:search');
        $instance->setDescription('Search Google Fonts catalog');

        return $instance;
    }
}
