<?php

namespace ContainerW0Rb4xE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFontsStatusCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'NeuralGlitch\GoogleFonts\Command\FontsStatusCommand' shared autowired service.
     *
     * @return \NeuralGlitch\GoogleFonts\Command\FontsStatusCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/neuralglitch/google-fonts/src/Command/FontsStatusCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/filesystem/Filesystem.php';

        $container->privates['NeuralGlitch\\GoogleFonts\\Command\\FontsStatusCommand'] = $instance = new \NeuralGlitch\GoogleFonts\Command\FontsStatusCommand('dev', false, (\dirname(__DIR__, 4).'/assets/fonts.json'), (\dirname(__DIR__, 4).'/assets/fonts'), ($container->privates['filesystem'] ??= new \Symfony\Component\Filesystem\Filesystem()));

        $instance->setName('gfonts:status');
        $instance->setDescription('Show Google Fonts configuration and status');

        return $instance;
    }
}
