<?php

namespace ContainerW0Rb4xE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFontDownloaderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'NeuralGlitch\GoogleFonts\Service\FontDownloader' shared autowired service.
     *
     * @return \NeuralGlitch\GoogleFonts\Service\FontDownloader
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/neuralglitch/google-fonts/src/Service/FontDownloader.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/filesystem/Filesystem.php';

        return $container->privates['NeuralGlitch\\GoogleFonts\\Service\\FontDownloader'] = new \NeuralGlitch\GoogleFonts\Service\FontDownloader((\dirname(__DIR__, 4).'/assets/fonts'), ($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), ($container->privates['NeuralGlitch\\GoogleFonts\\Service\\GoogleFontsApi'] ?? $container->load('getGoogleFontsApiService')), ($container->privates['filesystem'] ??= new \Symfony\Component\Filesystem\Filesystem()));
    }
}
