<?php

namespace ContainerW0Rb4xE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGoogleFontsRuntimeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'NeuralGlitch\GoogleFonts\Twig\GoogleFontsRuntime' shared autowired service.
     *
     * @return \NeuralGlitch\GoogleFonts\Twig\GoogleFontsRuntime
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/twig/twig/src/Extension/RuntimeExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/neuralglitch/google-fonts/src/Twig/GoogleFontsRuntime.php';

        return $container->privates['NeuralGlitch\\GoogleFonts\\Twig\\GoogleFontsRuntime'] = new \NeuralGlitch\GoogleFonts\Twig\GoogleFontsRuntime(false, (\dirname(__DIR__, 4).'/assets/fonts.json'), $container->parameters['google_fonts.defaults'], ($container->privates['asset_mapper'] ?? self::getAssetMapperService($container)));
    }
}
