<?php

namespace ContainerW0Rb4xE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGoogleFontsApiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'NeuralGlitch\GoogleFonts\Service\GoogleFontsApi' shared autowired service.
     *
     * @return \NeuralGlitch\GoogleFonts\Service\GoogleFontsApi
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/neuralglitch/google-fonts/src/Service/GoogleFontsApi.php';

        return $container->privates['NeuralGlitch\\GoogleFonts\\Service\\GoogleFontsApi'] = new \NeuralGlitch\GoogleFonts\Service\GoogleFontsApi(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), NULL, 3600);
    }
}
