<?php

namespace ContainerW0Rb4xE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMainControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.im4p1JQ.App\Controller\Front\MainController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.im4p1JQ.App\\Controller\\Front\\MainController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'carouselImageRepository' => ['privates', 'App\\Repository\\CarouselImageRepository', 'getCarouselImageRepositoryService', true],
            'homeSectionRepository' => ['privates', 'App\\Repository\\HomeSectionRepository', 'getHomeSectionRepositoryService', true],
        ], [
            'carouselImageRepository' => 'App\\Repository\\CarouselImageRepository',
            'homeSectionRepository' => 'App\\Repository\\HomeSectionRepository',
        ]))->withContext('App\\Controller\\Front\\MainController::index()', $container);
    }
}
