<?php

namespace ContainerW0Rb4xE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRubricInfoRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\RubricInfoRepository' shared autowired service.
     *
     * @return \App\Repository\RubricInfoRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/RubricInfoRepository.php';

        return $container->privates['App\\Repository\\RubricInfoRepository'] = new \App\Repository\RubricInfoRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
