<?php

namespace ContainerW0Rb4xE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResourcesControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2jP_vBB.App\Controller\Front\ResourcesController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2jP_vBB.App\\Controller\\Front\\ResourcesController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'galleryImageRepository' => ['privates', 'App\\Repository\\GalleryImageRepository', 'getGalleryImageRepositoryService', true],
            'rubricInfoRepository' => ['privates', 'App\\Repository\\RubricInfoRepository', 'getRubricInfoRepositoryService', true],
        ], [
            'galleryImageRepository' => 'App\\Repository\\GalleryImageRepository',
            'rubricInfoRepository' => 'App\\Repository\\RubricInfoRepository',
        ]))->withContext('App\\Controller\\Front\\ResourcesController::index()', $container);
    }
}
