<?php

namespace ContainerW0Rb4xE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTrainingControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oFZcE36.App\Controller\Front\TrainingController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oFZcE36.App\\Controller\\Front\\TrainingController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'trainingSectionRepository' => ['privates', 'App\\Repository\\TrainingSectionRepository', 'getTrainingSectionRepositoryService', true],
            'rubricInfoRepository' => ['privates', 'App\\Repository\\RubricInfoRepository', 'getRubricInfoRepositoryService', true],
        ], [
            'trainingSectionRepository' => 'App\\Repository\\TrainingSectionRepository',
            'rubricInfoRepository' => 'App\\Repository\\RubricInfoRepository',
        ]))->withContext('App\\Controller\\Front\\TrainingController::index()', $container);
    }
}
