<?php

namespace ContainerW0Rb4xE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTeamSectionRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\TeamSectionRepository' shared autowired service.
     *
     * @return \App\Repository\TeamSectionRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/TeamSectionRepository.php';

        return $container->privates['App\\Repository\\TeamSectionRepository'] = new \App\Repository\TeamSectionRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
