<?php

namespace ContainerW0Rb4xE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWhoReportsControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8qDVmy4.App\Controller\Front\WhoReportsController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8qDVmy4.App\\Controller\\Front\\WhoReportsController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'rubricInfoRepository' => ['privates', 'App\\Repository\\RubricInfoRepository', 'getRubricInfoRepositoryService', true],
            'reportsRepository' => ['privates', 'App\\Repository\\ReportsRepository', 'getReportsRepositoryService', true],
        ], [
            'rubricInfoRepository' => 'App\\Repository\\RubricInfoRepository',
            'reportsRepository' => 'App\\Repository\\ReportsRepository',
        ]))->withContext('App\\Controller\\Front\\WhoReportsController::index()', $container);
    }
}
