<?php

namespace ContainerW0Rb4xE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWhoAssociationControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Front\WhoAssociationController' shared autowired service.
     *
     * @return \App\Controller\Front\WhoAssociationController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Front/WhoAssociationController.php';

        $container->services['App\\Controller\\Front\\WhoAssociationController'] = $instance = new \App\Controller\Front\WhoAssociationController();

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Front\\WhoAssociationController', $container));

        return $instance;
    }
}
