<?php

namespace ContainerW0Rb4xE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWhoTeamControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Oq5L5Qp.App\Controller\Front\WhoTeamController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Oq5L5Qp.App\\Controller\\Front\\WhoTeamController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'teamSectionRepository' => ['privates', 'App\\Repository\\TeamSectionRepository', 'getTeamSectionRepositoryService', true],
            'rubricInfoRepository' => ['privates', 'App\\Repository\\RubricInfoRepository', 'getRubricInfoRepositoryService', true],
            'teamRepository' => ['privates', 'App\\Repository\\TeamRepository', 'getTeamRepositoryService', true],
        ], [
            'teamSectionRepository' => 'App\\Repository\\TeamSectionRepository',
            'rubricInfoRepository' => 'App\\Repository\\RubricInfoRepository',
            'teamRepository' => 'App\\Repository\\TeamRepository',
        ]))->withContext('App\\Controller\\Front\\WhoTeamController::index()', $container);
    }
}
