<?php

namespace ContainerSocGkKB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_H3KOBraService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.H3KOBra' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\Back\\BackMainController::index' => ['privates', '.service_locator.wjUIYeS.App\\Controller\\Back\\BackMainController::index()', 'getBackMainControllerindexService', true],
            'App\\Controller\\Front\\ActionsBeninController::index' => ['privates', '.service_locator.YKtU2F0.App\\Controller\\Front\\ActionsBeninController::index()', 'getActionsBeninControllerindexService', true],
            'App\\Controller\\Front\\ActionsFranceController::index' => ['privates', '.service_locator.YwLLdgS.App\\Controller\\Front\\ActionsFranceController::index()', 'getActionsFranceControllerindexService', true],
            'App\\Controller\\Front\\ContactController::index' => ['privates', '.service_locator.8vsY0c0.App\\Controller\\Front\\ContactController::index()', 'getContactControllerindexService', true],
            'App\\Controller\\Front\\EulogyController::index' => ['privates', '.service_locator.6nm.BDv.App\\Controller\\Front\\EulogyController::index()', 'getEulogyControllerindexService', true],
            'App\\Controller\\Front\\MainController::index' => ['privates', '.service_locator.im4p1JQ.App\\Controller\\Front\\MainController::index()', 'getMainControllerindexService', true],
            'App\\Controller\\Front\\ResourcesController::index' => ['privates', '.service_locator.2jP_vBB.App\\Controller\\Front\\ResourcesController::index()', 'getResourcesControllerindexService', true],
            'App\\Controller\\Front\\TrainingController::index' => ['privates', '.service_locator.oFZcE36.App\\Controller\\Front\\TrainingController::index()', 'getTrainingControllerindexService', true],
            'App\\Controller\\Front\\WhoAssociationController::index' => ['privates', '.service_locator.TEfXQB1.App\\Controller\\Front\\WhoAssociationController::index()', 'getWhoAssociationControllerindexService', true],
            'App\\Controller\\Front\\WhoReportsController::index' => ['privates', '.service_locator.8qDVmy4.App\\Controller\\Front\\WhoReportsController::index()', 'getWhoReportsControllerindexService', true],
            'App\\Controller\\Front\\WhoTeamController::index' => ['privates', '.service_locator.Oq5L5Qp.App\\Controller\\Front\\WhoTeamController::index()', 'getWhoTeamControllerindexService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\Back\\BackMainController:index' => ['privates', '.service_locator.wjUIYeS.App\\Controller\\Back\\BackMainController::index()', 'getBackMainControllerindexService', true],
            'App\\Controller\\Front\\ActionsBeninController:index' => ['privates', '.service_locator.YKtU2F0.App\\Controller\\Front\\ActionsBeninController::index()', 'getActionsBeninControllerindexService', true],
            'App\\Controller\\Front\\ActionsFranceController:index' => ['privates', '.service_locator.YwLLdgS.App\\Controller\\Front\\ActionsFranceController::index()', 'getActionsFranceControllerindexService', true],
            'App\\Controller\\Front\\ContactController:index' => ['privates', '.service_locator.8vsY0c0.App\\Controller\\Front\\ContactController::index()', 'getContactControllerindexService', true],
            'App\\Controller\\Front\\EulogyController:index' => ['privates', '.service_locator.6nm.BDv.App\\Controller\\Front\\EulogyController::index()', 'getEulogyControllerindexService', true],
            'App\\Controller\\Front\\MainController:index' => ['privates', '.service_locator.im4p1JQ.App\\Controller\\Front\\MainController::index()', 'getMainControllerindexService', true],
            'App\\Controller\\Front\\ResourcesController:index' => ['privates', '.service_locator.2jP_vBB.App\\Controller\\Front\\ResourcesController::index()', 'getResourcesControllerindexService', true],
            'App\\Controller\\Front\\TrainingController:index' => ['privates', '.service_locator.oFZcE36.App\\Controller\\Front\\TrainingController::index()', 'getTrainingControllerindexService', true],
            'App\\Controller\\Front\\WhoAssociationController:index' => ['privates', '.service_locator.TEfXQB1.App\\Controller\\Front\\WhoAssociationController::index()', 'getWhoAssociationControllerindexService', true],
            'App\\Controller\\Front\\WhoReportsController:index' => ['privates', '.service_locator.8qDVmy4.App\\Controller\\Front\\WhoReportsController::index()', 'getWhoReportsControllerindexService', true],
            'App\\Controller\\Front\\WhoTeamController:index' => ['privates', '.service_locator.Oq5L5Qp.App\\Controller\\Front\\WhoTeamController::index()', 'getWhoTeamControllerindexService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\Back\\BackMainController::index' => '?',
            'App\\Controller\\Front\\ActionsBeninController::index' => '?',
            'App\\Controller\\Front\\ActionsFranceController::index' => '?',
            'App\\Controller\\Front\\ContactController::index' => '?',
            'App\\Controller\\Front\\EulogyController::index' => '?',
            'App\\Controller\\Front\\MainController::index' => '?',
            'App\\Controller\\Front\\ResourcesController::index' => '?',
            'App\\Controller\\Front\\TrainingController::index' => '?',
            'App\\Controller\\Front\\WhoAssociationController::index' => '?',
            'App\\Controller\\Front\\WhoReportsController::index' => '?',
            'App\\Controller\\Front\\WhoTeamController::index' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\Back\\BackMainController:index' => '?',
            'App\\Controller\\Front\\ActionsBeninController:index' => '?',
            'App\\Controller\\Front\\ActionsFranceController:index' => '?',
            'App\\Controller\\Front\\ContactController:index' => '?',
            'App\\Controller\\Front\\EulogyController:index' => '?',
            'App\\Controller\\Front\\MainController:index' => '?',
            'App\\Controller\\Front\\ResourcesController:index' => '?',
            'App\\Controller\\Front\\TrainingController:index' => '?',
            'App\\Controller\\Front\\WhoAssociationController:index' => '?',
            'App\\Controller\\Front\\WhoReportsController:index' => '?',
            'App\\Controller\\Front\\WhoTeamController:index' => '?',
        ]);

        if (isset($container->privates['.service_locator.H3KOBra'])) {
            return $container->privates['.service_locator.H3KOBra'];
        }

        return $container->privates['.service_locator.H3KOBra'] = $instance;
    }
}
