<?php

namespace ContainerSocGkKB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBackMainControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wjUIYeS.App\Controller\Back\BackMainController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'carouselImageRepository' => ['privates', 'App\\Repository\\CarouselImageRepository', 'getCarouselImageRepositoryService', true],
            'homeSectionRepository' => ['privates', 'App\\Repository\\HomeSectionRepository', 'getHomeSectionRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'carouselImageRepository' => 'App\\Repository\\CarouselImageRepository',
            'homeSectionRepository' => 'App\\Repository\\HomeSectionRepository',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\Back\\BackMainController::index()', $container);

        if (isset($container->privates['.service_locator.wjUIYeS.App\\Controller\\Back\\BackMainController::index()'])) {
            return $container->privates['.service_locator.wjUIYeS.App\\Controller\\Back\\BackMainController::index()'];
        }

        return $container->privates['.service_locator.wjUIYeS.App\\Controller\\Back\\BackMainController::index()'] = $instance;
    }
}
