<?php

namespace ContainerSocGkKB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContactSectionRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\ContactSectionRepository' shared autowired service.
     *
     * @return \App\Repository\ContactSectionRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/ContactSectionRepository.php';

        return $container->privates['App\\Repository\\ContactSectionRepository'] = new \App\Repository\ContactSectionRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
