<?php

namespace ContainerSocGkKB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFontsLockCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'NeuralGlitch\GoogleFonts\Command\FontsLockCommand' shared autowired service.
     *
     * @return \NeuralGlitch\GoogleFonts\Command\FontsLockCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/neuralglitch/google-fonts/src/Command/FontsLockCommand.php';

        $container->privates['NeuralGlitch\\GoogleFonts\\Command\\FontsLockCommand'] = $instance = new \NeuralGlitch\GoogleFonts\Command\FontsLockCommand(($container->privates['NeuralGlitch\\GoogleFonts\\Service\\FontLockManager'] ?? $container->load('getFontLockManagerService')), \dirname(__DIR__, 4));

        $instance->setName('gfonts:lock');
        $instance->setDescription('Scan templates and lock all used fonts for production');

        return $instance;
    }
}
