<?php

namespace ContainerSocGkKB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFontLockManagerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'NeuralGlitch\GoogleFonts\Service\FontLockManager' shared autowired service.
     *
     * @return \NeuralGlitch\GoogleFonts\Service\FontLockManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/neuralglitch/google-fonts/src/Service/FontLockManager.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/filesystem/Filesystem.php';

        return $container->privates['NeuralGlitch\\GoogleFonts\\Service\\FontLockManager'] = new \NeuralGlitch\GoogleFonts\Service\FontLockManager((\dirname(__DIR__, 4).'/assets/fonts'), (\dirname(__DIR__, 4).'/assets/fonts.json'), ($container->privates['NeuralGlitch\\GoogleFonts\\Service\\FontDownloader'] ?? $container->load('getFontDownloaderService')), ($container->privates['filesystem'] ??= new \Symfony\Component\Filesystem\Filesystem()));
    }
}
