<?php

namespace ContainerSocGkKB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFontsStatusCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.NeuralGlitch\GoogleFonts\Command\FontsStatusCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.NeuralGlitch\\GoogleFonts\\Command\\FontsStatusCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('gfonts:status', [], 'Show Google Fonts configuration and status', false, #[\Closure(name: 'NeuralGlitch\\GoogleFonts\\Command\\FontsStatusCommand')] fn (): \NeuralGlitch\GoogleFonts\Command\FontsStatusCommand => ($container->privates['NeuralGlitch\\GoogleFonts\\Command\\FontsStatusCommand'] ?? $container->load('getFontsStatusCommandService')));
    }
}
