<?php

namespace ContainerSocGkKB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFontsWarmCacheCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'NeuralGlitch\GoogleFonts\Command\FontsWarmCacheCommand' shared autowired service.
     *
     * @return \NeuralGlitch\GoogleFonts\Command\FontsWarmCacheCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/neuralglitch/google-fonts/src/Command/FontsWarmCacheCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/filesystem/Filesystem.php';

        $container->privates['NeuralGlitch\\GoogleFonts\\Command\\FontsWarmCacheCommand'] = $instance = new \NeuralGlitch\GoogleFonts\Command\FontsWarmCacheCommand(($container->privates['NeuralGlitch\\GoogleFonts\\Service\\FontDownloader'] ?? $container->load('getFontDownloaderService')), (\dirname(__DIR__, 4).'/assets/fonts.json'), ($container->privates['filesystem'] ??= new \Symfony\Component\Filesystem\Filesystem()));

        $instance->setName('gfonts:warm-cache');
        $instance->setDescription('Pre-warm font cache from manifest file');

        return $instance;
    }
}
