<?php

namespace ContainerSocGkKB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFontsSearchCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.NeuralGlitch\GoogleFonts\Command\FontsSearchCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.NeuralGlitch\\GoogleFonts\\Command\\FontsSearchCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('gfonts:search', [], 'Search Google Fonts catalog', false, #[\Closure(name: 'NeuralGlitch\\GoogleFonts\\Command\\FontsSearchCommand')] fn (): \NeuralGlitch\GoogleFonts\Command\FontsSearchCommand => ($container->privates['NeuralGlitch\\GoogleFonts\\Command\\FontsSearchCommand'] ?? $container->load('getFontsSearchCommandService')));
    }
}
