<?php

namespace ContainerSocGkKB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFranceSectionRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\FranceSectionRepository' shared autowired service.
     *
     * @return \App\Repository\FranceSectionRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/FranceSectionRepository.php';

        return $container->privates['App\\Repository\\FranceSectionRepository'] = new \App\Repository\FranceSectionRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
