<?php

namespace ContainerSocGkKB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSectionRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\SectionRepository' shared autowired service.
     *
     * @return \App\Repository\SectionRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/SectionRepository.php';

        return $container->privates['App\\Repository\\SectionRepository'] = new \App\Repository\SectionRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
