<?php

namespace ContainerSocGkKB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWhoAssociationControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TEfXQB1.App\Controller\Front\WhoAssociationController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TEfXQB1.App\\Controller\\Front\\WhoAssociationController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'associationSectionRepository' => ['privates', 'App\\Repository\\AssociationSectionRepository', 'getAssociationSectionRepositoryService', true],
            'rubricInfoRepository' => ['privates', 'App\\Repository\\RubricInfoRepository', 'getRubricInfoRepositoryService', true],
        ], [
            'associationSectionRepository' => 'App\\Repository\\AssociationSectionRepository',
            'rubricInfoRepository' => 'App\\Repository\\RubricInfoRepository',
        ]))->withContext('App\\Controller\\Front\\WhoAssociationController::index()', $container);
    }
}
