<?php

namespace Container0SxzGTi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFontsImportCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'NeuralGlitch\GoogleFonts\Command\FontsImportCommand' shared autowired service.
     *
     * @return \NeuralGlitch\GoogleFonts\Command\FontsImportCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/neuralglitch/google-fonts/src/Command/FontsImportCommand.php';

        $container->privates['NeuralGlitch\\GoogleFonts\\Command\\FontsImportCommand'] = $instance = new \NeuralGlitch\GoogleFonts\Command\FontsImportCommand(($container->privates['NeuralGlitch\\GoogleFonts\\Service\\FontDownloader'] ?? $container->load('getFontDownloaderService')));

        $instance->setName('gfonts:import');
        $instance->setDescription('Import and download a Google Font for local use');

        return $instance;
    }
}
