<?php

namespace Container0SxzGTi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFontsWarmCacheCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.NeuralGlitch\GoogleFonts\Command\FontsWarmCacheCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.NeuralGlitch\\GoogleFonts\\Command\\FontsWarmCacheCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('gfonts:warm-cache', [], 'Pre-warm font cache from manifest file', false, #[\Closure(name: 'NeuralGlitch\\GoogleFonts\\Command\\FontsWarmCacheCommand')] fn (): \NeuralGlitch\GoogleFonts\Command\FontsWarmCacheCommand => ($container->privates['NeuralGlitch\\GoogleFonts\\Command\\FontsWarmCacheCommand'] ?? $container->load('getFontsWarmCacheCommandService')));
    }
}
